---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hello-world
spec:
  podSelector:
    matchLabels:
      app: hello-world
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: hello
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    - from:
        - podSelector:
            matchLabels:
              app: world
      ports:
        - protocol: TCP
          port: 443
