---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: world
spec:
  podSelector:
    matchLabels:
      app: world
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: hello-world
      ports:
        - protocol: TCP
          port: 443
