---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: world
  name: world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
      - name: network-multitool
        image: praqma/network-multitool:alpine-extra
