---
apiVersion: v1
kind: Service
metadata:
  name: postgres-{{- include "safeVer" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
  selector:
    app: postgres-{{- include "useVer" . }}
  type: ClusterIP