---
apiVersion: v1
kind: Service
metadata:
  name: back-front-{{- include "safeVer" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: web
      port: {{ .Values.frontend.port }}
    - name: api
      port: {{ .Values.backend.port }}
  selector:
    app: back-front-{{- include "useVer" . }}
  type: ClusterIP