---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: 13-02-prod
  labels:
    app: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: "init-sleep"
        image: "busybox:latest"
        imagePullPolicy: "IfNotPresent"
        command: ['sleep', '5']
      containers:
      - name: back
        image: prividen/some-test-backend:0.2.2
        volumeMounts:
          - name: shared-folder
            mountPath: /static
        ports:
        - containerPort: 9000
        env:
          - name: DATABASE_URL
            value: postgres://postgres:postgres@postgres:5432/news
          - name: JOKES_API_URL
            value: "http://joke-server/joke/any"
      volumes:
        - name: shared-folder
          persistentVolumeClaim:
            claimName: shared-folder-volume-claim
