---
apiVersion: v1
kind: Service
metadata:
  name: back-front
  namespace: 13-01-test
spec:
  ports:
    - name: web
      port: 80
    - name: api
      port: 9000
  selector:
    app: back-front
  type: ClusterIP